name: Benchmark Java Sequences

on:
  push:
    branches: [ bench ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    name: Run benchmarks
    steps:
      - uses: actions/checkout@v2
        with:
          ref: bench
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn clean install
      - run: java -jar target/benchmarks.jar -f 5 -r 5 -w 1
